from urllib.request import urlopen

# Define Trello URL's.
studentData = [
    "https://trello.com/b/uaCT48b5/chronospatial.json",
    "https://trello.com/b/rq2mYJNn/public-trello-boards.json"
]

# Define constants. 
startingBracket = "["
comma = ","
endingBracket = "]"

# Convert Strings to Bytes due to encoding issues.
startingBracket = str.encode(startingBracket)
comma = str.encode(comma)
endingBracket = str.encode(endingBracket)

# Iterate through the student data array, append to a variable. Read in JSON generated by Trello's API (generates bytes).
iterator = 0
combinedData = b''
while iterator < len(studentData):
    if (len(studentData) - iterator == 1):
        combinedData = combinedData + urlopen(studentData[iterator]).read() 
    else: 
        combinedData = combinedData + urlopen(studentData[iterator]).read() + comma
    iterator = iterator + 1

# Add starting and ending bracket (valid JSON object).
combinedData = startingBracket + combinedData + endingBracket

# Writing combined Byte array to a file which can be used for analysis.
with open('combinedData.json', 'wb') as f:
    f.write(combinedData)