import sys
import time
from urllib.request import urlopen

# Define Trello URL's based on 'student-urls.txt' file. 
studentData = []
try: 
    with open('urls.txt', 'r') as f:
        studentData = f.readlines()
        studentData = [line.rstrip('\n') for line in open('urls.txt')]
except:
    print("Couldn't find 'url.txt'. Ensure that it's in the same directory.")
    time.sleep(15)
    sys.exit()

# Define constants and convert to Bytes (due to encoding).
startingBracket = str.encode("[")
comma = str.encode(",")
endingBracket = str.encode("]")

# Iterate through the student data array. Read in JSON generated by Trello's API (generates bytes). Doesn't add a comma to the last entry.
iterator = 0
combinedData = b''
while iterator < len(studentData):
    if (len(studentData) - iterator == 1):
        combinedData = combinedData + urlopen(studentData[iterator]).read() 
    else: 
        combinedData = combinedData + urlopen(studentData[iterator]).read() + comma
    iterator = iterator + 1

# Write combined Byte array to a file.
with open('trello-data.json', 'wb') as f:
    f.write(startingBracket + combinedData + endingBracket)