from urllib.request import urlopen

# Defining variables to combine multiple JSON files together.
startingBracket = "["
comma = ","
endingBracket = "]"

# Converting Strings to Bytes.
startingBracket = str.encode(startingBracket)
comma = str.encode(comma)
endingBracket = str.encode(endingBracket)

# Reading in the JSON generated by Trello's API (generates bytes). Needs to be converted into an array.
stu1Data = urlopen("https://trello.com/b/uaCT48b5/chronospatial.json").read()
stu2Data = urlopen("https://trello.com/b/rq2mYJNn/public-trello-boards.json").read()

# Creating a new JSON file and loading student data. Needs to be converted to iterate through an array.
with open('stu1.json', 'wb') as stu1:
    stu1.write(startingBracket)
    stu1.write(stu1Data)
    stu1.write(comma)

with open('stu2.json', 'wb') as stu2:
    stu2.write(stu2Data)
    stu2.write(endingBracket)

# Combining data into one file. Needs to have opening and ending brackets as well as commas.
with open('combinedFiles.json') as f:
