from urllib.request import urlopen

# Define Trello URL's based on 'student-urls.txt' file. 
studentData = []
try: 
    with open('student-urls.txt', 'r') as f:
        studentData = f.readlines()
        studentData = [line.rstrip('\n') for line in open('student-urls.txt')]
except:
    print("Couldn't find students-url.txt. Please make sure it's in the same directory as this executable.")

# Define constants. 
startingBracket = "["
comma = ","
endingBracket = "]"

# Convert Strings to Bytes (due to encoding).
startingBracket = str.encode(startingBracket)
comma = str.encode(comma)
endingBracket = str.encode(endingBracket)

# Iterate through the student data array. Read in JSON generated by Trello's API (generates bytes).
iterator = 0
combinedData = b''
while iterator < len(studentData):
    if (len(studentData) - iterator == 1):
        combinedData = combinedData + urlopen(studentData[iterator]).read() 
    else: 
        combinedData = combinedData + urlopen(studentData[iterator]).read() + comma
    iterator = iterator + 1

# Add starting and ending bracket (to create a valid JSON object).
combinedData = startingBracket + combinedData + endingBracket

# Write combined Byte array to a file which can be used for analysis.
with open('combinedData.json', 'wb') as f:
    f.write(combinedData)

print("Success!")